name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Generate image tag
        id: generate-tag
        run: |
          output=$(python mandrel_image_versions.py)
          echo "::set-output name=tag::$output"

      - name: Print tag
        run: echo "${{ steps.generate-tag.outputs.tag }}"

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: maven-jdk-mandrel-builder
          tags: latest ${{ github.sha }} ${{ steps.generate-tag.outputs.tag }}
          dockerfiles: ./maven-jdk-mandrel-builder.Dockerfile
          
      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/qiot
          username: ${{ secrets.QUAY_GH_USER }}
          password: ${{ secrets.QUAY_GH_TOKEN }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
